import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  UserButton,
  OrganizationSwitcher,
  OrganizationProfile,
  
} from '@clerk/nextjs'
import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes'
import LeftSidebar from "@/components/shared/LeftSidebar";
import RightSidebar from "@/components/shared/RightSidebar";
import Topbar from "@/components/shared/Topbar";

import type { Appearance } from '@clerk/types';

import { Geist, Geist_Mono, Neonderthaw } from 'next/font/google'
import { Roboto } from 'next/font/google';
import '../globals.css'
import { currentUser } from '@clerk/nextjs/server';
import { UploadErrorBoundary } from '@/components/Error-Boundary';

const geist = Geist({
  variable : '--font-geist'
})
const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  display: 'swap', // This is recommended for performance
  
  variable: '--font-roboto', 
});

export const metadata: Metadata = {
  title: '---- MY NExT JS APP  -----',
  description: 'Generated by create next app',
}

export default async function  RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  // console.log('CLERK User at app > root > layout' , user)
  // CLERK APPEARACNES 

  const user = await currentUser();
  const isFirstTime = !!user?.publicMetadata?.isFirstTimeUser;
  
  const userButtonAppearance = {
    elements: {
      userButtonAvatarBox: "w-64", // Custom width and height
      userButtonPopoverCard: "w-64", // Custom background for the popover card
      userButtonPopoverMain : '',
      userButtonPopoverActionButton: "text-red-600", // Custom text color for action buttons
      userButtonPopoverActionButton__signOut : '',
      userButtonPopoverRootBox : 'bg-red w-128'
      ,rootBox: "w-128",                // The outermost wrapper
      userButtonTrigger: "...",      // The clickable avatar button
      userButtonAvatarImage: "...",  // The actual <img> tag
      userButtonPopoverActionButton__addAccount: "text-purple-500 hover:bg-purple-50",
      // Styles the "Sign out of all accounts" button
      userButtonPopoverActionButton__signOutAll: "text-red-500 border-t border-gray-100",
    },
  };
  const customAppearance = {
   
     cssLayerName :  'clerk',
    // theme: shadesOfPurple ,
      variables: {
        colorPrimary: 'green',
        colorTextSecondary : 'violet',
        colorBackground: '', // Deep, charcoal background
        colorForeground: 'purple',
        colorText: 'green', // Light, distinct text
        fontFamily: 'var(--font-roboto)', 
      },
      

  layout: {
    // Place social buttons at the bottom
    socialButtonsPlacement: 'bottom',
    // Change the placement of the logo to outside the card (for a cleaner look)
    shimmer: false
  },

  elements: {
        card: {
          backgroundColor: "black", //ORGANIZATIN ADD BUTTON BACKGROUUND
          border: "1px solid rgba(255,255,255,0.1)"
        },
        formButtonPrimary: {
        className: "!bg-indigo-600 hover:!bg-indigo-700 !transition-all duration-300 rounded-lg !py-3 text-lg !font-bold !uppercase"
      },

      }
  } as Appearance


  return (
    <UploadErrorBoundary>
    <ClerkProvider
     appearance= {customAppearance}
     >
      <html lang="en" className={`h-screen ${geist.className} ${roboto.className}`} >
        <body className={`antialiased mx-8 h-[100vh] flex flex-col gap-0 justify-between text-gray-900`} >
          <nav className="flex px-8 justify-between bg-gray-700 text-white">
            <Topbar/>
            <p className='font-black self-center'>THIS IS INSIDE IN THE ROOT LAYOUT and TOPBAR</p>
            
            {/* // ORGANIZATIONS CLERK */}
            {/* <OrganizationProfile /> */}
            <OrganizationSwitcher />

            {/* SIGNED USER PROFILE */}
            <SignedIn>
              <UserButton appearance={userButtonAppearance}/>
            </SignedIn>
          </nav>

        <div className='flex justify-between'>
          <LeftSidebar />
          
          {children}

        <RightSidebar isFirstTime={isFirstTime} />
        </div>
        </body>
      </html>
    </ClerkProvider>
  </UploadErrorBoundary>
  )
}