import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  UserButton,
  OrganizationSwitcher,
  OrganizationProfile,
  
} from '@clerk/nextjs'
import { currentUser } from '@clerk/nextjs/server';
import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes'
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";
import Topbar from "@/components/shared/Topbar";

import type { Appearance } from '@clerk/types';

// import { Geist, Geist_Mono, Neonderthaw } from 'next/font/google'
import { Roboto } from 'next/font/google';
import '../globals.css'

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'], // Specify all weights you plan to use
  subsets: ['latin'],
  display: 'swap', // This is recommended for performance
  
  variable: '--font-roboto', 
});

export const metadata: Metadata = {
  title: '---- MY NExT JS APP  -----',
  description: 'Generated by create next app',
}

export default async function  RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  
  // CLERK APPEARACNES 

  const userButtonAppearance = {
    elements: {
      userButtonAvatarBox: "w-10 h-10", // Custom width and height
      userButtonPopoverCard: "bg-gray-700", // Custom background for the popover card
      userButtonPopoverActionButton: "text-red-600", // Custom text color for action buttons
      userButtonPopoverActionButton__signOut : ''
    },
  };

  
    const customAppearance = {
      // 1. Base Theme: Start with a dark theme
      // theme: shadesOfPurple ,
      cssLayerName :  'clerk',
      variables: {
        colorPrimary: 'white', // A bright, distinct primary color
        colorTextSecondary : 'white', // SECURED BYH CLERK

        colorBackground: '', // Deep, charcoal background
        
        colorForeground: 'red',
        colorText: 'green', // Light, distinct text

        fontFamily: 'var(--font-roboto)', 
        
      },
      
  // 3. Layout: Change structural elements
  layout: {
    // Replace the default logo with your own
    logoImageUrl: 'https://your-domain.com/path-to-your-logo.svg',
    // Place social buttons at the bottom
    socialButtonsPlacement: 'bottom',
    // Change the placement of the logo to outside the card (for a cleaner look)
    shimmer: false
  },

  elements: {
        card: {
          backgroundColor: "black", // CSS Object style
          border: "1px solid rgba(255,255,255,0.1)"
        },
        // Use className for Tailwind strings
        formButtonPrimary: {
        className: "!bg-indigo-600 hover:!bg-indigo-700 !transition-all !duration-300 !rounded-lg !py-3 !text-lg !font-bold !uppercase"
      },
      // This is likely the one failing. Add !shadow-none to remove the default Clerk inner shadow
      formFieldInput: {
        // className: "!bg-red-500 !border-gray-600 !text-white !rounded-md focus:!ring-blue-500 focus:!border-blue-500 !shadow-none"
        backgroundColor : 'red',
        margin : '50px !important', 
      },
      footerActionText: {
        className: "!text-indigo-400 hover:!text-indigo-300 !font-medium"
      },
      // Hiding the footer
      footer: {
        display: "none !important"
      },
      }
  } as Appearance


  return (
    <ClerkProvider
     appearance= {customAppearance}
     >
      <html lang="en" className={`h-screen ${roboto.className}`} >
        <body className={` ${roboto.variable} antialiased mx-8 h-[100vh] flex flex-col gap-0 justify-between text-white`} >
          <nav className="flex px-8 justify-between bg-gray-800 text-white">
            <Topbar/>
            <p className='font-black self-center'>THIS IS INSIDE IN THE ROOT LAYOUT and TOPBAR</p>
            
            {/* // ORGANIZATIONS CLERK */}
            {/* <OrganizationProfile /> */}
            <OrganizationSwitcher />

            {/* SIGNED USER PROFILE */}
            <SignedIn>
              <UserButton appearance={userButtonAppearance}/>
            </SignedIn>
          </nav>

        <div className='flex justify-between h-[90vh]'>
          <LeftSidebar />
          {children}
          
          <RightSidebar />
        </div>
          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  )
}