import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  UserButton,
  OrganizationSwitcher,
  OrganizationProfile

} from '@clerk/nextjs'
import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes'
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";
import Topbar from "@/components/shared/Topbar";

import type { Appearance } from '@clerk/types';

import { Geist, Geist_Mono, Neonderthaw } from 'next/font/google'
import { Roboto } from 'next/font/google';
import '../globals.css'

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'], // Specify all weights you plan to use
  subsets: ['latin'],
  display: 'swap', // This is recommended for performance
  
  // Optional: Create a CSS variable name for use in Tailwind/CSS
  variable: '--font-roboto', 
});

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: '---- MY NExT JS APP  -----',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  // CLERK APPEARACNES 

  const userButtonAppearance = {
    elements: {
      userButtonAvatarBox: "w-10 h-10", // Custom width and height
      userButtonPopoverCard: "bg-blue-100", // Custom background for the popover card
      userButtonPopoverActionButton: "text-red-600", // Custom text color for action buttons
      userButtonPopoverActionButton__signOut : ''
    },
  };

  
 const customAppearance = {
  // 1. Base Theme: Start with a dark theme
  // theme: shadesOfPurple ,
  cssLayerName :  'clerk',

  // 2. Variables: Override primary colors, background, and fonts
  variables: {
    colorPrimary: 'black', // A bright, distinct primary color
    colorTextSecondary : 'white', // SECURED BYH CLERK

    colorBackground: '', // Deep, charcoal background
    colorNeutral: 'black', //MAIN TEXT
    
    colorForegroud: 'black',
    colorText: 'black', // Light, distinct text

    fontFamily: 'var(--font-roboto)', 
    
  },
  
  // 3. Layout: Change structural elements
  layout: {
    // Replace the default logo with your own
    logoImageUrl: 'https://your-domain.com/path-to-your-logo.svg',
    // Place social buttons at the bottom
    socialButtonsPlacement: 'bottom',
    // Change the placement of the logo to outside the card (for a cleaner look)
    shimmer: false
  },

  // 4. Elements: Apply custom CSS classes to specific UI parts
  elements: {
    // Style the main container (card)
    card: {
    },
    // Style the primary button (e.g., Sign In/Sign Up buttons)
    formButtonPrimary: 'bg-indigo-600 hover:bg-indigo-700 transition-all duration-300 rounded-lg py-3 text-lg font-bold uppercase',
    
    // Style the text/input fields
    formFieldInput: 'bg-gray-700 border-gray-600 text-gray-100 rounded-md focus:ring-blue-500 focus:border-blue-500',
    
    // Style the text of the secondary button (e.g., "Forgot Password")
    footerActionText: 'text-indigo-400 hover:text-indigo-300 font-medium',
    
    // Remove the default Clerk logo/link in the footer
    footer: {
      display: 'none', // Directly hides the element
    },
    
   
  },
} as Appearance


  return (
    <ClerkProvider
     appearance= {customAppearance}
     >
      <html lang="en" className='h-screen'>
        <body className={` ${roboto.variable}  antialiased mx-8 h-[100vh] flex flex-col gap-0 justify-between`}>
          <nav className="flex px-8 justify-between bg-gray-900 text-white">
            <Topbar/>
            <p className='font-black self-center'>THIS IS INSIDE IN THE ROOT LAYOUT and TOPBAR</p>
            
            {/* // ORGANIZATIONS CLERK */}

            {/* <OrganizationProfile /> */}
            <OrganizationSwitcher />

            {/* SIGNED USER PROFILE */}
            <SignedIn>
              <UserButton appearance={userButtonAppearance}/>
            </SignedIn>
          </nav>

        <div className='flex justify-between h-[90vh]'>
          <LeftSidebar />
          {children}
          
          <RightSidebar />
        </div>
          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  )
}