import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark , neobrutalism } from '@clerk/themes'
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  const localization = {
  signUp: {
    start: {
      title: "Welcome Back Custom!",
      subtitle: 'to access {{applicationName}}',
    },
    emailCode: {
      subtitle: 'to access {{applicationName}}',
    },
  },

   signIn: {
    },

    formButtonPrimary: 'LETS GO!',
}

  return (
    <ClerkProvider

    localization={localization}

    appearance={{
      cssLayerName : 'clerk',
      elements : {
      //  footerAction: 'bg-black' ,
      //  footer : 'bg-black',
      // userButtonPopoverActionsuserButtonPopoverActions__singleSession : 'bg-black',
          userButtonPopoverActions__singleSession : {
          // backgroundColor : '#49247A'
          },
          userPreview : 'bg-black',
          userPreview__userButton : 'bg-black',
          userButtonAvatarBox : 'bg-black font-larger', 
          userButton : "bg-black",
         footer: {
         fontSize: 14,
        textTransform: 'none',  
      }
      },
    
    }}
    >
      <html lang='en'>
        <body className={`${inter.className} grid grid-flow-col w-screen h-screen justify-center items-center gap-6`}>
          <p className="bg-red-400 text-white p-5 text-center
">            THIS IS SIGN-OUT ( Auth ) PAGE
          </p>    
        
      {children}
      
      </body>
      </html>
    </ClerkProvider>
  );
}