import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { shadesOfPurple } from "@clerk/themes"
import { shadcn } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  const localization = {
    
  signUp: {
    start: {
      title: "Fill Up To Acess ChatApp!",
      subtitle: '',
      actionText: "", 
    },
    emailCode: {
      subtitle: 'to access {{applicationName}}',
    },
  },
  signIn : { 

    start: {
      // THIS CHANGES THE SUB-HEADER TEXT
      subtitle: "Please enter your credensials", 
      title: "Welcome to ChatApp", 
      actionText: "Don't have an account? ", 
    },
  }
}

  return (
    <ClerkProvider

    localization={localization}
    appearance={{
      // baseTheme: shadcn,
      //   variables: {
      //     // You can still override specific shadcn colors here if needed
      //     colorPrimary: "hsl(var(--primary))", 
      //   },
      cssLayerName : 'clerk',  
      layout : {
      socialButtonsVariant : 'iconButton',
      // headerSubtitle: "Glad to see you again!",
      logoPlacement : 'inside',
      socialButtonsPlacement : 'bottom'
    },

      elements : {
        // card : {
        //  backgroundImage: `
        // radial-gradient(circle, white 190px, transparent 1px),             /* Sharp Center */
        // radial-gradient(circle, rgba(255,255,255,0.5) 10px, transparent 4px), /* Soft Glow */
        // // repeating-linear-gradient(-130deg, white, white 5px, white 5px, white 50px) /* Background */`,
        // // Size 1: auto (for stripes) | Size 2: 20px (for dots)
        // backgroundSize: 'auto, 15px 15px',
        // backgroundPosition: 'center , 10px 90px',
        // },
   
      userButtonPopoverActions__singleSession : {
      backgroundColor : '#49247A'
      },
        userPreview : 'bg-indigo-500',
        userPreview__userButton : 'bg-red-500',
        userButtonAvatarBox : 'bg-black font-larger', 
        userButton : "bg-blue-500",
      },
    
    }}
    >
      <html lang='en' >
        <body className={`${inter.className} grid grid-flow-col bg-slate-600 w-screen h-screen justify-center items-center gap-6`
        } >
        
      {children}
      
      </body>
      </html>
    </ClerkProvider>
  );
}